CREATE PROCEDURE UPDATELEASE

@ID int,
@STARTDATE DATE,
@FIRSTPAYMENTDATE DATE,
@MONTHLYPAYMENT MONEY,
@MONTHLYPAYMENTCOUNT INT,
@VECHILEID INT,
@CUSTOMERID INT,
@TERMS NTEXT

AS 

BEGIN

UPDATE DBO.Leases

SET 
[START DATE] = @STARTDATE,
[FIRST PAYMENT DATE] = @FIRSTPAYMENTDATE,
[MONTHLY PAYMENT] = @MONTHLYPAYMENT,
[MONTHLY PAYMENT COUNT] = @MONTHLYPAYMENTCOUNT,
VEHICLEID = @VECHILEID,
CUSTOMERID = @CUSTOMERID,
TERMS =@TERMS
Where 
ID = @ID

END